name: farm-todo-app
services:
  nginx:
    image: nginx:stable-perl
    container_name: farm-todo-nginx
    ports:
    - 8000:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - frontend
    - backend
    

  backend:
    image: farm-todo/backend
    build: ./backend
    container_name: farm-todo-backend
    expose:
      - 3001
    ports:
    - 8001:3001
    volumes:
    - ./backend:/usr/src/app
    environment:
      MONGO_DB_URI: mongodb+srv://2018200000042:farm-stack@cluster0.uihqr2w.mongodb.net/farm?retryWrites=true&w=majority&appName=Cluster0

    command: "python src/server.py"
    

  frontend:
    image: node:22
    user: "node"
    working_dir: /home/node/app
    container_name: farm-todo-frontend
    volumes:
    - ./frontend:/home/node/app
    expose:
    - 3000
    ports:
    - 3000:3000
    environment:
      - NODE_ENV=development
      - WD_SOCKET+PORT=0
    command: "npm start"

  

