- name: Update yum cache
  dnf:
    update_cache: true
  become: true

- name: Install {{ java_version }}
  package: 
    name: " {{ java_version }}"
    state: present
  become: true

- name: Ensure JAVA is installed
  dnf:
    name: java
    state: present


