- name: Basic Ansible playbook
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files: 
    - ../group_vars/dev
  tasks:
    - name: Print a Message
      ansible.builtin.debug:
        var:  app_port
      become: true
